strategy_name: "Finder"
strategy_config_file: "config-seeker.json"
user_dir: "/freqtrade/user_data"
base_config_file: "config.json"
result_dir: "hyperopt_results"
hyperopt_loss: "MultiMetricLoss"
spaces_generate:
  - buy
  - sell
  - roi
  - stoploss
  - trades
spaces_finetune:
  - trailing
timerange_generate: "20210101-20231201"
timerange_finetune: "20210101-20231201"
timerange_backtest: "20210101-20231201"
timeframe: "12h"
timeframe_detail_generate: "1h"
timeframe_detail_finetune: "15m"
timeframe_detail_backtest: "1m"
stake_amount_backtest: "unlimited"
fee: 0.001
epochs_generate: 500
epochs_finetune: 100
max_strategies: 50
min_trades: 250
min_total_profit: 20000.0
min_objective: -4.0
