strategy_name: "Seeker"
user_dir: "/freqtrade/user_data"
result_dir: "hyperopt_results"
base_config_file: "config.json"
strategy_config_file: "config-seeker.json"
strategy_param_file: "strategies/Seeker.json"
hyperopt_loss: "MultiMetricLoss"
timerange: "20211101-20231101"
timeframe: "12h"
timeframe_detail_finetune: "1h"
timeframe_detail_backtest: "15m"
stake_amount_backtest: 500.0
fee: 0.001
epoch_count: 500
max_strategies: 50
min_total_profit: 10000.0
min_objective: -3.25
